apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: wz8y31d4q-python 
  janus-idp.io/tekton: wz8y31d4q-python
  backstage.io/kubernetes-id: wz8y31d4q-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wz8y31d4q-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml