apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wz8y31d4q-python
  janus-idp.io/tekton: wz8y31d4q-python
  backstage.io/kubernetes-id: wz8y31d4q-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wz8y31d4q-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
