apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wz8y31d4q-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wz8y31d4q-python 
  name: wz8y31d4q-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wz8y31d4q-python 
